#!/usr/bin/env bash

set -e

echo "Writing rev ($3) to nix/$2-rev.txt"
echo $3 > nix/$2-rev.txt

echo "Fetching and writing sha to nix/$2-sha.txt"
set -x
nix-prefetch-url \
  https://github.com/$1/$2/archive/$3.tar.gz \
  --unpack \
  > nix/$2-sha.txt
